services:
  patient-service-db:
    container_name: patient-service-pgsql-db
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-patient_service_database}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-9000}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  patient-service:
    image: patient-service:latest
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_URL: patient-service-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-patient_service_database}
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9096
    ports:
      - "${PATIENT_SERVICE_API_PORT:-8085}:8085"
    depends_on:
      patient-service-db:
        condition: service_healthy

  billing-service:
    image: billing-service:latest
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - "${BILLING_SERVICE_API_PORT:-8086}:8086"
      - "${BILLING_SERVICE_GRPC_PORT:-9096}:9096"

  analytics-service:
    image: analytics-service:latest
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    ports:
      - "${ANALYTICS_SERVICE_API_PORT:-8087}:8087"
      - "${ANALYTICS_SERVICE_GRPC_PORT:-9096}:9096"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092



  kafka:
    container_name: kafka
    image: apache/kafka:4.1.1
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

networks:
  default:
    name: patient_internal_network

volumes:
  postgres:
